### ISSUE TITLE
[PE-D] Undo and done does not throw an error when executing an invalid String at the index with both character and numbers

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-3/tp#154]
![Screenshot 2021-10-29 at 5.17.43 PM.png](https://raw.githubusercontent.com/williamlamjy/ped/main/files/1a5d2bfc-d194-4c80-9c17-952be01a2564.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: williamlamjy/ped#8

**Comment by crabnuggets** [comment]
A possible solution would be to extract the third segment of the user input (the segment where the index of the task/event should be indicated) and use the `Integer.parseInt(thirdSegment)` method instead.

**Comment by Alvinlj00** [comment]
I don't consider this a bug, it is a valid command accepted by the application so the user does not have to worry too much about typos. Also, since the done and undo command accepts multiple indexes at once, as long as these indexes are separated by non-digit characters, all of them should be accepted.
